# Generated by Django 3.2.4 on 2021-07-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('residencial', 'residencial'), ('comercial', 'comercial')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombPropietario', models.CharField(max_length=100)),
                ('costoDept', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cuartos', models.IntegerField(verbose_name='Número de Cuartos')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='administrativo.edificio')),
            ],
        ),
    ]
